### ISSUE TITLE
Got an error when downloading LAION5B

### ISSUE THREAD

**Issue by viyjy** [rom1504/img2dataset#183]
Hi, I follow instructions from [LAION5B](https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion5B.md) to download the dataset by using EMR cluster. However, when I run `./img2dataset.pex download.py`, I got the following error. I didn't find any useful information from this error, any suggestions will be appreciated.

```
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/07/01 23:35:28 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
22/07/01 23:35:39 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Attempted to request executors before the AM has registered!
/home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/.bootstrap/pex/dist_metadata.py:397: PEXWarning: Ignoring 8 `Requires` fields in /home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/.deps/scikit_image-0.18.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl metadata:
1.) Requires: numpy (>= 1.16.5)
2.) Requires: scipy (>= 1.0.1)
3.) Requires: matplotlib (>= 2.0.0,!=3.0.0)
4.) Requires: networkx (>= 2.0)
5.) Requires: pillow (>= 4.3.0,!=7.1.0,!=7.1.1)
6.) Requires: imageio (>= 2.3.0)
7.) Requires: tifffile (>= 2019.7.26)
8.) Requires: PyWavelets (>= 1.1.1)

You may have issues using the 'scikit-image' distribution as a result.
More information on this workaround can be found here:
  https://github.com/pantsbuild/pex/issues/1201#issuecomment-791715585

  pex_warnings.warn(
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/__main__.py", line 86, in <module>
    bootstrap_pex(__entry_point__)
  File "/home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/.bootstrap/pex/pex_bootstrapper.py", line 567, in bootstrap_pex
    pex.PEX(entry_point).execute()
  File "/home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/.bootstrap/pex/pex.py", line 516, in execute
    sys.exit(self._wrap_coverage(self._wrap_profiling, self._execute))
  File "/home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/.bootstrap/pex/pex.py", line 423, in _wrap_coverage
    return runner(*args)
  File "/home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/.bootstrap/pex/pex.py", line 454, in _wrap_profiling
    return runner(*args)
  File "/home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/.bootstrap/pex/pex.py", line 548, in _execute
    return self.execute_interpreter()
  File "/home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/.bootstrap/pex/pex.py", line 623, in execute_interpreter
    return self.execute_content(arg, content)
  File "/home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/.bootstrap/pex/pex.py", line 701, in execute_content
    return cls.execute_ast(name, program, argv0=argv0)
  File "/home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/.bootstrap/pex/pex.py", line 719, in execute_ast
    exec_function(program, globals_map)
  File "/home/hadoop/.pex/unzipped_pexes/35508899abf6ae5e0acf275e7cc94027ba7c67d9/.bootstrap/pex/compatibility.py", line 94, in exec_function
    exec (ast, globals_map, locals_map)
  File "download.py", line 38, in <module>
    download(
  File "/home/hadoop/.pex/installed_wheels/03d735998c85eee7fcf7cb2f0f1d3dd288172b2f6f6991b93b20655434d7353e/img2dataset-1.31.0-py3-none-any.whl/img2dataset/main.py", line 175, in download
    distributor_fn(
  File "/home/hadoop/.pex/installed_wheels/03d735998c85eee7fcf7cb2f0f1d3dd288172b2f6f6991b93b20655434d7353e/img2dataset-1.31.0-py3-none-any.whl/img2dataset/distributor.py", line 87, in pyspark_distributor
    failed_shards = run(reader)
  File "/home/hadoop/.pex/installed_wheels/03d735998c85eee7fcf7cb2f0f1d3dd288172b2f6f6991b93b20655434d7353e/img2dataset-1.31.0-py3-none-any.whl/img2dataset/distributor.py", line 80, in run
    for batch in batcher(gen, subjob_size):
  File "/home/hadoop/.pex/installed_wheels/03d735998c85eee7fcf7cb2f0f1d3dd288172b2f6f6991b93b20655434d7353e/img2dataset-1.31.0-py3-none-any.whl/img2dataset/distributor.py", line 75, in batcher
    for first in iterator:
  File "/home/hadoop/.pex/installed_wheels/03d735998c85eee7fcf7cb2f0f1d3dd288172b2f6f6991b93b20655434d7353e/img2dataset-1.31.0-py3-none-any.whl/img2dataset/reader.py", line 167, in __iter__
    shards, number_shards = self._save_to_arrow(input_file, start_shard_id)
  File "/home/hadoop/.pex/installed_wheels/03d735998c85eee7fcf7cb2f0f1d3dd288172b2f6f6991b93b20655434d7353e/img2dataset-1.31.0-py3-none-any.whl/img2dataset/reader.py", line 91, in _save_to_arrow
    df = pq.read_table(file, columns=columns_to_read)
  File "/home/hadoop/.pex/installed_wheels/8f77f93c06e6ecaae6b9009047b31b3ee1e90a8c22bdfdb9e4cfd38121f55f0d/pyarrow-7.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl/pyarrow/parquet.py", line 1996, in read_table
    return dataset.read(columns=columns, use_threads=use_threads,
  File "/home/hadoop/.pex/installed_wheels/8f77f93c06e6ecaae6b9009047b31b3ee1e90a8c22bdfdb9e4cfd38121f55f0d/pyarrow-7.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl/pyarrow/parquet.py", line 1831, in read
    table = self._dataset.to_table(
  File "pyarrow/_dataset.pyx", line 323, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 298, in pyarrow._dataset.Dataset.scanner
  File "pyarrow/_dataset.pyx", line 2117, in pyarrow._dataset.Scanner.from_dataset
  File "pyarrow/_dataset.pyx", line 1995, in pyarrow._dataset._populate_builder
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(NSFW) in URL: string
TEXT: string
WIDTH: int32
HEIGHT: int32
similarity: double
hash: int64
punsafe: float
pwatermark: float
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib64/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/usr/lib64/python3.8/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
Command exiting with ret '1'
```

**Comment by rom1504** [comment]
pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(NSFW) in URL: string
TEXT: string
WIDTH: int32
HEIGHT: int32
similarity: double
hash: int64
punsafe: float
pwatermark: float



That's the error. If you used the joined dataset, you need to adapt
the fields in the command line. The save additional columns need to
list columns that exist, so that's not NSFW but for punsafe

**Comment by viyjy** [comment]
Thanks.
