### ISSUE TITLE
[Error] pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(URL) in similarity: double

### ISSUE THREAD

**Issue by ternaus** [rom1504/img2dataset#207]
```
img2dataset==1.33.0
```

Downloaded the `laion-high-resolution` with 

```
img2dataset --url_list laion-high-resolution --input_format "parquet"\
         --url_col "URL" --caption_col "TEXT" --output_format files\
           --output_folder laion-high-resolution --processes_count 16 --thread_count 64 --image_size 1024\
            --resize_only_if_bigger=True --resize_mode="keep_ratio" --skip_reencode=True \
             --save_additional_columns '["similarity","hash","punsafe","pwatermark","LANGUAGE"]'
```

Worked well.

At some point needed to stop the download.

Trying to continue, but get an error:

```
Sharding file number 1 of 533 called /mnt/wdc6tb/data/laion-super-resolution/laion-high-resolution/00000.parquet
0it [00:01, ?it/s]
Traceback (most recent call last):
  File "/home/vladimir/anaconda3/bin/img2dataset", line 8, in <module>
    sys.exit(main())
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/img2dataset/main.py", line 191, in main
    fire.Fire(download)
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/img2dataset/main.py", line 184, in download
    max_shard_retry,
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/img2dataset/distributor.py", line 36, in multiprocessing_distributor
    failed_shards = run(reader)
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/img2dataset/distributor.py", line 31, in run
    for (status, row) in tqdm(process_pool.imap_unordered(downloader, gen)):
  File "/home/vladimir/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/vladimir/anaconda3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(URL) in similarity: double

```

**Comment by rom1504** [comment]
You can't use the same folder for input and output

**Comment by ternaus** [comment]
Thanks.

Could you please update the Readme that uses the same input and output path at https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion-high-resolution.md

?

**Comment by rom1504** [comment]
Yes done!
