### ISSUE TITLE
simple_example.py: Running it on Windows 10 and WSL2: remove rmtree(output_dir), add freeze_support(), wandb.login(), ssl: update-ca-certificates

### ISSUE THREAD

**Issue by Twenkid** [rom1504/img2dataset#219]
I tried to run the simple_example.py benchmark on Windows 10 with Anaconda (Py 3.10.4) and on WSL2/Ubuntu 20.04 (no virtual environment, Py 3.10.8). 
I'm sharing what I discovered:

```git clone https://github.com/rom1504/img2dataset ```
cd ... --> .../img2dataset/examples/ 
python simple_example.py

In order the test data location to match url_list="../tests/..."

Edited code:

```python
from img2dataset import download
import shutil
import multiprocessing
import os
import wandb

output_dir = os.path.abspath("bench2")
print("\n==============\n"+output_dir+"\n============")
#if os.path.exists(output_dir):
#  shutil.rmtree(output_dir)

def main():
    #wandb.login(key="...your-key...")
    os.environ["WANDB_API_KEY"] = "...your-key..."
    os.environ["WANDB_MODE"] = "offline" #"online"
    download(
    processes_count=8,
    thread_count=32,
    url_list="../tests/test_files/test_10000.parquet",
    image_size=256,
    output_folder=output_dir,
    output_format="files",
    input_format="parquet",
    url_col="URL",
    caption_col="TEXT",
    enable_wandb=True,
    number_sample_per_shard=1000,
    distributor="multiprocessing",
)
    
if __name__ == "__main__":
    multiprocessing.freeze_support()
    main()

# rm -rf bench
```

1. There were multiprocessing library errors. In order to fix them I put download() in another function main(), also the script first calls multiprocessing.freeze_support() - it seems that's required for Windows.  https://stackoverflow.com/questions/24374288/where-to-put-freeze-support-in-a-python-script. Without that there are ```spawn``` errors: 
```An attempt has been made to start a new process before the current process has finished its bootstrapping phase.```

2. I don't know is it Windows specific or it is a bug in the original script, but I had to comment the removal of the output directory:

```
 if os.path.exists(output_dir):
   shutil.rmtree(output_dir)
```

Otherwise the script couldn't find the files which were expected/the files were not where the script expected them to be and it crashed:

```
   File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\img2dataset\downloader.py", line 94, in __call__
    self.download_shard(row)
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\img2dataset\downloader.py", line 111, in download_shard
    with fs.open(shard_path, "rb") as f:
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\fsspec\spec.py", line 1009, in open
    f = self._open(
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\fsspec\implementations\local.py", line 155, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\fsspec\implementations\local.py", line 250, in __init__
    self._open()
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\fsspec\implementations\local.py", line 255, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'Z:/img2dataset/examples/bench2/_tmp/1.feather'
shard 1 failed with error [Errno 2] No such file or directory: 'Z:/img2dataset/examples/bench2/_tmp/1.feather'
10it [00:00, 26.45it/s]
Retried 1 times, but 10 shards still failed. You may restart the same command to retry again.

==============
Z:\img2dataset\examples\bench2
============
wandb: Tracking run with wandb version 0.12.21
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
wandb: Waiting for W&B process to finish... (success).
wandb:
wandb: You can sync this run to the cloud by running:
wandb: wandb sync Z:\img2dataset\examples\wandb\offline-run-20221112_002755-2eyezkx1
wandb: Find logs at: .\wandb\offline-run-20221112_002755-2eyezkx1\logs
Traceback (most recent call last):
  File "Z:\img2dataset\examples\simple_example.py", line 54, in <module>
    main()
  File "Z:\img2dataset\examples\simple_example.py", line 36, in main
    download(
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\img2dataset\main.py", line 187, in download
    fs.rm(tmp_dir, recursive=True)
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\fsspec\implementations\local.py", line 149, in rm
    os.remove(p)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Z:/img2dataset/examples/bench2/_tmp'
```

3. WAND registration is required and login if one hasn't used that service and the library requires  an api-key:  https://docs.wandb.ai/quickstart
```
  import wand 
  wandb.login(key="...api-key...")```
```

4. In WSL/Ubuntu 20.04 it run once?, but then after running in Windows there were errors with wandb, TransientError, ConnectionError, "entering retry loop". 

```
wandb: Network error (TransientError), entering retry loop.
wandb: Network error (ConnectionError), entering retry loop.
wandb: Network error (ConnectionError), entering retry loop.
```

One may guess it was a quota overload? There was a discussion that it was unlikely as the limit was high enough. An update of the SSL certificate was suggested and SSL appears in the wandb log: ```urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'InvImg.autofunds.com'. (_ssl.c:997)>0.0001 1``` 

It seems some of the links for the test collection point to resources with a more strict access.

I updated the certificates with a suggested command:

 ```sudo update-ca-certificates``` was applied in WSL, however it didn't help.
 
 ```
 wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Network error (ConnectionError), entering retry loop.
wandb: Network error (ConnectionError), entering retry loop.
```

In Windows there are no problems with that.

5. A workaround for "ConnectionError" (and in general if we don't need to share that log) is to run in offline mode:

```python
os.environ["WANDB_API_KEY"] = "yourkey"
os.environ["WANDB_MODE"] = "offline"
```

However it didn't resolve the error in WSL and the script froze before starting to download.

```
wandb: Tracking run with wandb version 0.12.21
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
```

* I was not using a venv in WSL, if that possibly could cause such problems, but the error didn't seem of that kind, IDK.

6. There were errors with the encoding of some of the texts (downloaded resources) that had to be printed (Cyrillic, cp-1251) which produced a lot of exceptions, possibly slowing the script down a bit, unable to convert Unicode to windows-1251 charset. 

In order to display Cyrillic in Windows consoles, appropriate font has to be selected, such as Lucida, however switching to one didn't help with the errors (maybe the symbols are emojis or other alphabets characters, not Cyrillic symbols.

For changing the console's font:

(Left click on Terminal's icon --> Properties --> Font --> Lucida Console)

![image](https://user-images.githubusercontent.com/23367640/201441061-8fc2ad6f-7dac-483b-8693-8c258f829601.png)

```
Traceback (most recent call last):
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\img2dataset\downloader.py", line 255, in download_shard
    sample_writer.write(
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\img2dataset\writer.py", line 264, in write
    f.write(str(caption))
  File "C:\Users\xxxx\.conda\envs\clip\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xfa' in position 15: character maps to <undefined>
Sample 880 failed to download: 'charmap' codec can't encode character '\xfa' in position 15: character maps to <undefined>
```

Some of the symbols:

https://unicode-table.com/en/30FB/
https://unicode-table.com/en/search/?q=fffd
[Inverted Exclamation Mark](https://unicode-table.com/en/00A1/)
[Latin-1 Supplement](https://unicode-table.com/en/blocks/latin-1-supplement/)

```
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 103: character maps to <undefined>
Sample 997 failed to download: 'charmap' codec can't encode character '\ufffd' in position 103: character maps to <undefined>
8it [02:46, 17.87s/it]worker  - success: 0.879 - failed to download: 0.114 - failed to resize: 0.007 - images per sec: 10 - count: 1000
total   - success: 0.876 - failed to download: 0.114 - failed to resize: 0.009 - images per sec: 50 - count: 8000
9it [02:54, 15.04s/it]worker  - success: 0.872 - failed to download: 0.119 - failed to resize: 0.009 - images per sec: 25 - count: 1000
total   - success: 0.876 - failed to download: 0.115 - failed to resize: 0.009 - images per sec: 54 - count: 9000
10it [02:59, 17.99s/it]
worker  - success: 0.870 - failed to download: 0.119 - failed to resize: 0.011 - images per sec: 19 - count: 1000
total   - success: 0.875 - failed to download: 0.115 - failed to resize: 0.010 - images per sec: 58 - count: 10000
```

## Sample final result (run from Windows)

```
wandb: Waiting for W&B process to finish... (success).
wandb:
wandb:
wandb: Run history:
wandb:               total/count ▁▂▃▃▄▅▆▆▇█
wandb:  total/failed_to_download ▁▅▆█▇▇▇▇▇▇
wandb:    total/failed_to_resize ▁▃▃▂██▅▃▃▄
wandb:         total/img_per_sec ▁▄▆█▅▆▇▇▇█
wandb:             total/success █▄▃▁▂▁▂▂▂▂
wandb:              worker/count ▁▁▁▁▁▁▁▁▁▁
wandb: worker/failed_to_download ▁▅▄█▂▆▁▄▅▅
wandb:   worker/failed_to_resize ▃▄▃▃█▄▁▁▃▅
wandb:        worker/img_per_sec ▄▄▃▃▅▄▂▁█▅
wandb:            worker/success █▄▅▁▆▃█▆▄▄
wandb:
wandb: Run summary:
wandb:               total/count 10000
wandb:  total/failed_to_download 0.1153
wandb:    total/failed_to_resize 0.0096
wandb:         total/img_per_sec 57.77218
wandb:             total/success 0.8751
wandb:              worker/count 1000
wandb: worker/failed_to_download 0.119
wandb:   worker/failed_to_resize 0.011
wandb:        worker/img_per_sec 19.49059
wandb:            worker/success 0.87
wandb:
wandb: You can sync this run to the cloud by running:
wandb: wandb sync Z:\img2dataset\examples\wandb\offline-run-20221111_222858-gecyo4g0
wandb: Find logs at: .\wandb\offline-run-20221111_222858-gecyo4g0\logs
(clip) Z:\img2dataset\examples>python simple_example.py
```

...

7. Regarding the error when the script removes the directory in the beginning: I didn't know/don't know why it is supposed to do it, cleaning past data or something. I suspected as a possible source of the error the transform of the path, maybe the absolute path generation. I checked the download() function in main.py and added debug lines, however strangely they did not print, while the code reached to "Starting to download"...  (I'm missing something or the output disappears through the threads.)

```python
#img2dataset/main.py ...
  """Download is the main entry point of img2dataset, it uses multiple processes and download multiple files"""
    print(f"####download()")
    config_parameters = dict(locals())

    def make_path_absolute(path):
        fs, p = fsspec.core.url_to_fs(path)
        if fs.protocol == "file":
            return os.path.abspath(p)
        return path
    print(f"make_path_absolute({output_folder})=") #doesn't print
    output_folder = make_path_absolute(output_folder)
    print(f"{output_folder}") #doesn't print
    url_list = make_path_absolute(url_list)
    ...
   print("Starting the downloading of this file") #that prints
      if distributor == "multiprocessing":
          distributor_fn = multiprocessing_distributor
```

The errors when the dir is removed (each process or thread that are being spawned encounters it):

```
(clip) Z:\img2dataset\examples>python simple_example.py
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Appending key for api.wandb.ai to your netrc file: C:\Users\xxxx/.netrc
**Starting the downloading of this file**
Sharding file number 1 of 1 called Z:/img2dataset/tests/test_files/test_10000.parquet
0it [00:00, ?it/s]File sharded in 10 shards
Downloading starting now, check your bandwidth speed (with bwm-ng)your cpu (with htop), and your disk usage (with iotop)!
Traceback (most recent call last):
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\img2dataset\downloader.py", line 94, in __call__
    self.download_shard(row)
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\img2dataset\downloader.py", line 111, in download_shard
    with fs.open(shard_path, "rb") as f:
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\fsspec\spec.py", line 1009, in open
    f = self._open(
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\fsspec\implementations\local.py", line 155, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\fsspec\implementations\local.py", line 250, in __init__
    self._open()
  File "C:\Users\xxxx\.conda\envs\clip\lib\site-packages\fsspec\implementations\local.py", line 255, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'Z:/img2dataset/examples/bench/_tmp/0.feather'
shard 0 failed with error [Errno 2] No such file or directory: 'Z:/img2dataset/examples/bench/_tmp/0.feather'
1it [00:07,  7.14s/it]Traceback (most recent call last):
```
Etc.

* The Spawn error - it happened in WSL as well.

```
xxxxt@yyyy:/mnt/z/clipwin$ python3 ../bench.py
Starting the downloading of this file
Sharding file number 1 of 1 called /mnt/z/tests/test_files/test_10000.parquet
0it [00:00, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/z/bench.py", line 10, in <module>
    download(
  File "/home/tosh/.local/lib/python3.10/site-packages/img2dataset/main.py", line 107, in download
    logger_process.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/z/bench.py", line 10, in <module>
    download(

'''

**Comment by Twenkid** [comment]
In other runs in WSL, after printing wandb info:

1. if the output folder already exists, the script ends, the log is below (I guess that's related to why the original script removes the directory in the beginning). (It seems it's during the time of spawning of the process, which in this run are 8/32 threads): 

```
:/mnt/z/img2dataset/examples$ python3 simple_example.py
==============
/mnt/z/img2dataset/examples/bench2
============
Starting the downloading of this file
Sharding file number 1 of 1 called /mnt/z/img2dataset/tests/test_files/test_10000.parquet
0it [00:00, ?it/s]File sharded in 0 shards
Downloading starting now, check your bandwidth speed (with bwm-ng)your cpu (with htop), and your disk usage (with iotop)!
0it [00:00, ?it/s]

==============
/mnt/z/img2dataset/examples/bench2
============
wandb: Tracking run with wandb version 0.12.21
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
wandb: Waiting for W&B process to finish... (success).
wandb:
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /mnt/z/img2dataset/examples/wandb/offline-run-20221112_182250-v5jq0lff
wandb: Find logs at: ./wandb/offline-run-20221112_182250-v5jq0lff/logs
xxxx@xxxxxxxx:/mnt/z/img2dataset/examples$ cat  ./wandb/offline-run-20221112_182250-v5jq0lff/logs
cat: ./wandb/offline-run-20221112_182250-v5jq0lff/logs: Is a directory
xxxx@xxxxxxxx:/mnt/z/img2dataset/examples$ ls  ./wandb/offline-run-20221112_182250-v5jq0lff/logs
debug-internal.log  debug.log
xxxx@xxxxxxxx:/mnt/z/img2dataset/examples$ cat  ./wandb/offline-run-20221112_182250-v5jq0lff/logs/debug.log
2022-11-12 18:22:50,245 INFO    MainThread:112 [wandb_setup.py:_flush():76] Configure stats pid to 112
2022-11-12 18:22:50,246 INFO    MainThread:112 [wandb_setup.py:_flush():76] Loading settings from /home/tosh/.config/wandb/settings
2022-11-12 18:22:50,246 INFO    MainThread:112 [wandb_setup.py:_flush():76] Loading settings from /mnt/z/img2dataset/examples/wandb/settings
2022-11-12 18:22:50,246 INFO    MainThread:112 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***', 'mode': 'offline'}
2022-11-12 18:22:50,246 INFO    MainThread:112 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'examples/simple_example.py', 'program': '/mnt/z/img2dataset/examples/simple_example.py'}
2022-11-12 18:22:50,247 INFO    MainThread:112 [wandb_init.py:_log_setup():461] Logging user logs to /mnt/z/img2dataset/examples/wandb/offline-run-20221112_182250-v5jq0lff/logs/debug.log
2022-11-12 18:22:50,247 INFO    MainThread:112 [wandb_init.py:_log_setup():462] Logging internal logs to /mnt/z/img2dataset/examples/wandb/offline-run-20221112_182250-v5jq0lff/logs/debug-internal.log
2022-11-12 18:22:50,248 INFO    MainThread:112 [wandb_init.py:init():495] calling init triggers
2022-11-12 18:22:50,248 INFO    MainThread:112 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {'url_list': '../tests/test_files/test_10000.parquet', 'image_size': 256, 'output_folder': '/mnt/z/img2dataset/examples/bench2', 'processes_count': 8, 'resize_mode': 'border', 'resize_only_if_bigger': False, 'upscale_interpolation': 'lanczos', 'downscale_interpolation': 'area', 'encode_quality': 95, 'encode_format': 'jpg', 'skip_reencode': False, 'output_format': 'files', 'input_format': 'parquet', 'url_col': 'URL', 'caption_col': 'TEXT', 'thread_count': 32, 'number_sample_per_shard': 1000, 'extract_exif': True, 'save_additional_columns': None, 'timeout': 10, 'enable_wandb': True, 'wandb_project': 'img2dataset', 'oom_shard_count': 5, 'compute_md5': True, 'distributor': 'multiprocessing', 'subjob_size': 1000, 'retries': 0, 'disable_all_reencoding': False, 'min_image_size': 0, 'max_aspect_ratio': inf, 'incremental_mode': 'incremental', 'max_shard_retry': 1}
2022-11-12 18:22:50,248 INFO    MainThread:112 [wandb_init.py:init():548] starting backend
2022-11-12 18:22:50,249 INFO    MainThread:112 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-11-12 18:22:50,253 INFO    MainThread:112 [backend.py:ensure_launched():217] starting backend process...
2022-11-12 18:22:50,254 INFO    MainThread:112 [backend.py:ensure_launched():222] started backend process with pid: 143
2022-11-12 18:22:50,254 INFO    MainThread:112 [wandb_init.py:init():558] backend started and connected
2022-11-12 18:22:50,270 INFO    MainThread:112 [wandb_init.py:init():634] updated telemetry
2022-11-12 18:22:50,384 INFO    MainThread:112 [wandb_init.py:init():700] starting run threads in backend
2022-11-12 18:22:51,300 INFO    MainThread:112 [wandb_run.py:_console_start():1893] atexit reg
2022-11-12 18:22:51,304 INFO    MainThread:112 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-11-12 18:22:51,305 INFO    MainThread:112 [wandb_run.py:_redirect():1771] Redirecting console.
2022-11-12 18:22:51,311 INFO    MainThread:112 [wandb_run.py:_redirect():1827] Redirects installed.
2022-11-12 18:22:51,312 INFO    MainThread:112 [wandb_init.py:init():732] run started, returning control to user process
2022-11-12 18:22:51,479 INFO    MainThread:112 [wandb_run.py:_finish():1680] finishing run img2dataset/v5jq0lff
2022-11-12 18:22:51,481 INFO    MainThread:112 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-11-12 18:22:51,483 INFO    MainThread:112 [wandb_run.py:_restore():1834] restore
2022-11-12 18:22:54,324 INFO    MainThread:112 [wandb_run.py:_on_finish():1991] got exit ret:
2022-11-12 18:22:54,427 INFO    MainThread:112 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
local_info {
}

2022-11-12 18:22:55,554 INFO    MainThread:112 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-11-12 18:22:55,555 INFO    MainThread:112 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
```

However:

2. If the folder is empty, the script just hangs. It first prints/shows that it spawns the processes and then freezes.

```
xxx@xxx:/mnt/z/img2dataset/examples$ python3 simple_example.py

==============
/mnt/z/img2dataset/examples/bench3
============
Starting the downloading of this file
Sharding file number 1 of 1 called /mnt/z/img2dataset/tests/test_files/test_10000.parquet
0it [00:00, ?it/s]File sharded in 10 shards
Downloading starting now, check your bandwidth speed (with bwm-ng)your cpu (with htop), and your disk usage (with iotop)!

==============
/mnt/z/img2dataset/examples/bench3
============

==============
/mnt/z/img2dataset/examples/bench3
============

==============
/mnt/z/img2dataset/examples/bench3
============

==============
/mnt/z/img2dataset/examples/bench3
============

==============
/mnt/z/img2dataset/examples/bench3
============

==============
/mnt/z/img2dataset/examples/bench3
============

==============
/mnt/z/img2dataset/examples/bench3
============

==============
/mnt/z/img2dataset/examples/bench3
============

==============
/mnt/z/img2dataset/examples/bench3
============
wandb: Tracking run with wandb version 0.12.21
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.

```

**Comment by rom1504** [comment]
are you using a virtualenv ?

multiprocessing.freeze_support why ?

**Comment by Twenkid** [comment]
That was said in the beginning of the post:
>I tried to run the simple_example.py benchmark on Windows 10 with Anaconda (Py 3.10.4) >and on WSL2/Ubuntu 20.04 (no virtual environment, Py 3.10.8).

Multip.:  spawn errors in both Win and WSL and that was a suggestion in the Py's error message (see logs).

Well it seems the last run when I thought the WSL run hanged, it has been actually running, but without any immediate feedback to the terminal. I see the console has outputted the 
results later, so it worked. Now testing without freeze_ ... in WSL, but still with embracing download(...) in main()) -- it works either, the same behavior.

```bash
tosh@DESKTOP-LQSDBBS:/mnt/z/img2dataset/examples$ python3 simple_example.py
(...)
wandb: Tracking run with wandb version 0.12.21
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.

1it [05:20, 320.30s/it]worker  - success: 0.025 - failed to download: 0.975 - failed to resize: 0.000 - images per sec: 3 - count: 1000
total   - success: 0.025 - failed to download: 0.975 - failed to resize: 0.000 - images per sec: 3 - count: 1000
2it [05:25, 135.16s/it]worker  - success: 0.020 - failed to download: 0.980 - failed to resize: 0.000 - images per sec: 3 - count: 1000
total   - success: 0.022 - failed to download: 0.978 - failed to resize: 0.000 - images per sec: 6 - count: 2000
6it [05:28, 25.20s/it]worker  - success: 0.000 - failed to download: 1.000 - failed to resize: 0.000 - images per sec: 3 - count: 1000
total   - success: 0.015 - failed to download: 0.985 - failed to resize: 0.000 - images per sec: 9 - count: 3000
worker  - success: 0.000 - failed to download: 1.000 - failed to resize: 0.000 - images per sec: 3 - count: 1000
total   - success: 0.011 - failed to download: 0.989 - failed to resize: 0.000 - images per sec: 12 - count: 4000
worker  - success: 0.000 - failed to download: 1.000 - failed to resize: 0.000 - images per sec: 3 - count: 1000
total   - success: 0.009 - failed to download: 0.991 - failed to resize: 0.000 - images per sec: 16 - count: 5000
worker  - success: 0.000 - failed to download: 1.000 - failed to resize: 0.000 - images per sec: 3 - count: 1000
total   - success: 0.007 - failed to download: 0.993 - failed to resize: 0.000 - images per sec: 19 - count: 6000
worker  - success: 0.000 - failed to download: 1.000 - failed to resize: 0.000 - images per sec: 3 - count: 1000
total   - success: 0.006 - failed to download: 0.994 - failed to resize: 0.000 - images per sec: 22 - count: 7000
worker  - success: 0.000 - failed to download: 1.000 - failed to resize: 0.000 - images per sec: 3 - count: 1000
total   - success: 0.006 - failed to download: 0.994 - failed to resize: 0.000 - images per sec: 25 - count: 8000
9it [10:40, 63.58s/it]worker  - success: 0.000 - failed to download: 1.000 - failed to resize: 0.000 - images per sec: 3 - count: 1000
total   - success: 0.005 - failed to download: 0.995 - failed to resize: 0.000 - images per sec: 14 - count: 9000
10it [10:46, 64.63s/it]
worker  - success: 0.000 - failed to download: 1.000 - failed to resize: 0.000 - images per sec: 3 - count: 1000
total   - success: 0.004 - failed to download: 0.996 - failed to resize: 0.000 - images per sec: 16 - count: 10000
wandb: Waiting for W&B process to finish... (success).
wandb:
wandb:
wandb: Run history:
wandb:               total/count ▁▂▃▃▄▅▆▆▇█
wandb:  total/failed_to_download ▁▂▄▆▆▇▇███
wandb:    total/failed_to_resize ▁▁▁▁▁▁▁▁▁▁
wandb:         total/img_per_sec ▁▂▃▄▅▆▇█▅▅
wandb:             total/success █▇▅▃▃▂▂▁▁▁
wandb:              worker/count ▁▁▁▁▁▁▁▁▁▁
wandb: worker/failed_to_download ▁▂████████
wandb:   worker/failed_to_resize ▁▁▁▁▁▁▁▁▁▁
wandb:        worker/img_per_sec █▃▁▁▁▁▁▁▁▁
wandb:            worker/success █▇▁▁▁▁▁▁▁▁
wandb:
wandb: Run summary:
wandb:               total/count 10000
wandb:  total/failed_to_download 0.9955
wandb:    total/failed_to_resize 0.0
wandb:         total/img_per_sec 15.64649
wandb:             total/success 0.0045
wandb:              worker/count 1000
wandb: worker/failed_to_download 1.0
wandb:   worker/failed_to_resize 0.0
wandb:        worker/img_per_sec 3.121
wandb:            worker/success 0.0
wandb:
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /mnt/z/img2dataset/examples/wandb/offline-run-20221112_182821-cjngbpwf
wandb: Find logs at: ./wandb/offline-run-20221112_182821-cjngbpwf/logs
```

**Comment by rom1504** [comment]
Try to use virtual env in wsl2
