### ISSUE TITLE
pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(URL) in NSFW: string

### ISSUE THREAD

**Issue by qnyan** [rom1504/img2dataset#317]
when i download images with 
img2dataset --url_list laion400m-meta --input_format "parquet" --url_col "URL" --caption_col "TEXT" --output_format files --output_folder laion400m-data --processes_count 16 --thread_count 128 --image_size 256 --save_additional_columns '["NSFW","similarity","LICENSE"]' --timeout 10
but i failed.
this is the error:
Starting the downloading of this file
Sharding file number 1 of 4013 called /share/datasets_01/huggingface/gitLFS_dataset/laion400m-meta/
0it [00:02, ?it/s]
Traceback (most recent call last):
  File "/home/e00450/anaconda3/bin/img2dataset", line 8, in <module>
    sys.exit(main())
  File "/home/e00450/anaconda3/lib/python3.8/site-packages/img2dataset/main.py", line 262, in main
    fire.Fire(download)
  File "/home/e00450/anaconda3/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/e00450/anaconda3/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/e00450/anaconda3/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/e00450/anaconda3/lib/python3.8/site-packages/img2dataset/main.py", line 250, in download
    distributor_fn(
  File "/home/e00450/anaconda3/lib/python3.8/site-packages/img2dataset/distributor.py", line 36, in multiprocessing_distributor
    failed_shards = run(reader)
  File "/home/e00450/anaconda3/lib/python3.8/site-packages/img2dataset/distributor.py", line 31, in run
    for (status, row) in tqdm(process_pool.imap_unordered(downloader, gen)):
  File "/home/e00450/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/e00450/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(URL) in NSFW: string
similarity: double
LICENSE: string
caption: string
url: string
key: int64
original_width: int64
original_height: int64

A similar question has been asked, but it doesn't work.
Please help me

**Comment by tom666tom666** [comment]
This is the url of the line that reports the error：
https://www.gannett-cdn.com/presto/2018/09/15/PMCA/3d524e77-4c01-4a60-bfb9-c5514d162195-091518-ClassicCarShow-13.jpg?crop=2669,1999,x0,y0&amp;width=80&amp;height=60&amp;fit=bounds

**Comment by xywei00** [comment]
The error should be interpreted as
```
No match for FieldRef.Name(URL) in
[NSFW: string, similarity: double, LICENSE: string, caption: string, url: string, key: int64, original_width: int64, original_height: int64]
```
This means that your metadata contains fields `[NSFW, similarity, ..., original_height]`, but does not contain field `URL` (which you specify as `--url_col`. So probably you need to change `--url_col` instead of `--save_additional_columns`.
