### ISSUE TITLE
Temp dir removal - FileNotFoundError: ['mybucket/data/tests/test_1000_parquet/5/_tmp']

### ISSUE THREAD

**Issue by erezzarum** [rom1504/img2dataset#319]
Running img2dataset with parquet as both input and output, using s3 as well (input/output).
At the end of the download it tries to delete the temp dir created for the feather files, but this dir is already removed.
I have removed the "fs.rm(tmp_dir...)" line to debug, no error and temp dir is removed.

When output is not an S3, it works as expected.
It seems that it might be related to the implementation of fsspec and s3fs.
After the last shard to be read is removed (last feather file), the whole path will be removed.

i did not test it this on other object storage, As a directory on S3 is just a "placeholder" (prefix), if this is the last file in the prefix, it will remove the whole prefix.
It is also not creating the temp dir first, as there are no files, it will create the temp dir just when placing the first feather file, and also delete the whole path when removing the last feather file.

**Comment by wayne163** [comment]
+1 

I also ran into this problem on S3 storage. The error log is 

```log
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/img2dataset", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/img2dataset/main.py", line 262, in main
    fire.Fire(download)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/img2dataset/main.py", line 258, in download
    fs.rm(tmp_dir, recursive=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fsspec/asyn.py", line 115, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
  File "/home/ubuntu/.local/lib/python3.8/site-packages/s3fs/core.py", line 1865, in _rm
    paths = await self._expand_path(path, recursive=recursive)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fsspec/asyn.py", line 758, in _expand_path
    out = await self._expand_path([path], recursive, maxdepth)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/fsspec/asyn.py", line 782, in _expand_path
    raise FileNotFoundError(path)
FileNotFoundError: ['dataset-test/coyo-700m-webdataset-0608/_tmp']
```

**Comment by erezzarum** [comment]
I submitted a PR to handle this.
Thanks for the feedback
