### ISSUE TITLE
Error when importing cv2

### ISSUE THREAD

**Issue by awsankur** [rom1504/img2dataset#355]
```
Running:  ['img2dataset', '--input_format=parquet', '--url_col=URL', '--caption_col=TEXT', '--output_format=webdataset', '--url_list=/fsx/laion-art/parquet/laion-art.parquet_parts/part.0.parquet_parts/part.0.parquet', '--output_folder=/fsx/laion-art/tarfiles_raw/part.0.parquet', '--processes_count=192', '--thread_count=64', '--encode_quality=95', '--resize_mode=False']
/usr/local/lib/python3.8/dist-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/bin/img2dataset", line 5, in <module>
    from img2dataset import main
  File "/usr/local/lib/python3.8/dist-packages/img2dataset/__init__.py", line 3, in <module>
    from img2dataset.main import main
  File "/usr/local/lib/python3.8/dist-packages/img2dataset/main.py", line 7, in <module>
    from .resizer import Resizer
  File "/usr/local/lib/python3.8/dist-packages/img2dataset/resizer.py", line 3, in <module>
    import albumentations as A
  File "/usr/local/lib/python3.8/dist-packages/albumentations/__init__.py", line 5, in <module>
    from .augmentations import *
  File "/usr/local/lib/python3.8/dist-packages/albumentations/augmentations/__init__.py", line 2, in <module>
    from .blur.functional import *
  File "/usr/local/lib/python3.8/dist-packages/albumentations/augmentations/blur/__init__.py", line 1, in <module>
    from .functional import *
  File "/usr/local/lib/python3.8/dist-packages/albumentations/augmentations/blur/functional.py", line 5, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/cv2/typing/__init__.py", line 169, in <module>
    LayerId = cv2.dnn.DictValue
AttributeError: module 'cv2.dnn' has no attribute 'DictValue'
```

**Comment by rom1504** [comment]
I advise you create a virtual env then follow the instructions in the readme for installing img2dataset

**Comment by awsankur** [comment]
This is happening in a Nemo container on a slurm cluster. I am installing img2dataset with pip like the readme says.

**Comment by awsankur** [comment]
FYI. An older version of opencv-python-headless 4.8.0.74 seems to work
