### ISSUE TITLE
Process hangs at the end

### ISSUE THREAD

**Issue by kobiso** [rom1504/img2dataset#74]
I'm using this to download millions of images but sometimes (not every time) the process hangs forever at the end of the job.
Good thing is the process hangs when it almost finish the job.
Whenever it hangs, I had to terminate the process manually.
Has anyone experienced the same?

**Comment by rom1504** [comment]
Hi kobiso,
What is the stack trace when you kill such a stuck img2dataset ?
I've observed that issue only when some other lib was messing with multiprocessing in some way (in my case pyspark was changing some signals in multiprocessing preventing the pool terminate() from finishing)

**Comment by rom1504** [comment]
I just observed the same thing. I'll look into it. Might be related with the semaphore

**Comment by kobiso** [comment]
The stack trace is as below.
I guess it was stuck by below error.

```bash
Traceback (most recent call last):
  File "/root/anaconda3/envs/crawl/lib/python3.8/multiprocessing/pool.py", line 851, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/crawl/bin/img2dataset", line 33, in <module>
    sys.exit(load_entry_point('img2dataset', 'console_scripts', 'img2dataset')())
  File "/home/workspace/data-crawler/img2dataset/img2dataset/downloader.py", line 451, in main
    fire.Fire(download)
  File "/root/anaconda3/envs/crawl/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/anaconda3/envs/crawl/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/anaconda3/envs/crawl/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/workspace/data-crawler/img2dataset/img2dataset/downloader.py", line 420, in download
    for count, successes, failed_to_download, failed_to_resize, duration, status_dict in tqdm(
  File "/root/anaconda3/envs/crawl/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/root/anaconda3/envs/crawl/lib/python3.8/multiprocessing/pool.py", line 856, in next
    self._cond.wait(timeout)
  File "/root/anaconda3/envs/crawl/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by rom1504** [comment]
I believe this might be solved with the last changes I made.
If you see it again, please say.

**Comment by kobiso** [comment]
@rom1504 Thanks! I will test it and let you know.

**Comment by kobiso** [comment]
@rom1504 
So, I tested it with 1.20.2 version and it still hangs at the end.
Below is the output when I terminate the process by force.

```
worker  - success: 0.807 - failed to download: 0.154 - failed to resize: 0.039 - images per sec: 41 - count: 1
0000
1057it [7:52:21, 26.81s/it]
/root/anaconda3/envs/crawl/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracke
r: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

This is the config I used.

<details>
<summary>Config</summary>

```
{
    "_wandb": {
        "desc": null,
        "value": {
            "t": {
                "1": [
                    1,
                    5
                ],
                "3": [
                    16
                ],
                "4": "3.8.12",
                "5": "0.12.9",
                "8": [
                    5,
                    9
                ]
            },
            "framework": "torch",
            "start_time": 1642140287,
            "cli_version": "0.12.9",
            "is_jupyter_run": false,
            "python_version": "3.8.12",
            "is_kaggle_kernel": false
        }
    },
    "timeout": {
        "desc": null,
        "value": 5
    },
    "url_col": {
        "desc": null,
        "value": "url"
    },
    "url_list": {
        "desc": null,
        "value": "/home/data_zoo/0.json"
    },
    "image_size": {
        "desc": null,
        "value": 256
    },
    "caption_col": {
        "desc": null,
        "value": "caption"
    },
    "compute_md5": {
        "desc": null,
        "value": true
    },
    "distributor": {
        "desc": null,
        "value": "multiprocessing"
    },
    "resize_mode": {
        "desc": null,
        "value": "border"
    },
    "subjob_size": {
        "desc": null,
        "value": 1000
    },
    "enable_wandb": {
        "desc": null,
        "value": true
    },
    "extract_exif": {
        "desc": null,
        "value": true
    },
    "input_format": {
        "desc": null,
        "value": "json"
    },
    "thread_count": {
        "desc": null,
        "value": 256
    },
    "output_folder": {
        "desc": null,
        "value": "/home/data_zoo"
    },
    "output_format": {
        "desc": null,
        "value": "files"
    },
    "skip_reencode": {
        "desc": null,
        "value": false
    },
    "wandb_project": {
        "desc": null,
        "value": "img2dataset"
    },
    "encode_quality": {
        "desc": null,
        "value": 95
    },
    "min_size_limit": {
        "desc": null,
        "value": 32
    },
    "oom_shard_count": {
        "desc": null,
        "value": 5
    },
    "processes_count": {
        "desc": null,
        "value": 40
    },
    "resize_only_if_bigger": {
        "desc": null,
        "value": true
    },
    "upscale_interpolation": {
        "desc": null,
        "value": "lanczos"
    },
    "downscale_interpolation": {
        "desc": null,
        "value": "area"
    },
    "number_sample_per_shard": {
        "desc": null,
        "value": 10000
    },
    "save_additional_columns": {
        "desc": null,
        "value": null
    }
}
```

</details>

**Comment by rom1504** [comment]
I still have no idea what is causing your issue (and I don't reproduce :( ), but I made a bunch of changes in recent weeks (notably switching to spawn method of multiprocessing) so I think maybe it could have solved this
could you give it another try?

**Comment by D0miH** [comment]
Hey Romain,
just a heads-up, that I am experiencing the same issue. I am trying to download the CC12M dataset and copied the command from your example [here](https://github.com/rom1504/img2dataset/blob/main/dataset_examples/cc12m.md). The only thing I changed was the number of processes and threads to match the hardware of my machine. 

I noticed that the downloading gets apparently stuck on 4 shards. I am not sure if this is helping, but in my case, it were the shards `00011.*`,` 00173.*`, `00613.*`, `00716.*`.

**Comment by D0miH** [comment]
Ok, so I investigated this a bit and I think this might be specific to the CC12M dataset. 
I found that in the dataset, some URLs are moved. As an example, the image URL `http://www.dogtrainingbasics.com/wp-content/uploads/2014/08/dog-meme-12.jpg` was permanently moved to `http://lg-dene.fdcservers.net/10GBtest.zip`. I am not sure if after downloading, the file is checked whether it is indeed an image file. However, I also noticed, that the server of the 10 GB zip file is also very slow. This is probably why the program is not exiting because it is download the 10 GB file for quite some time. 

@rom1504 Any idea how one could fix this? Check whether the file ending of the file that should be downloaded from the new URL is indeed an image file? Or maybe one could read the file of the response chunk by chunk and cancel the download if the speed is very low?

**Comment by rom1504** [comment]
We tried to implement timeout at https://github.com/rom1504/img2dataset/pull/153 but it was significantly slower.

We could try again i guess

**Comment by D0miH** [comment]
Great, thanks for making me aware of #153! I tried the code with the timeout and now CC12M is successfully downloading and finishing in reasonable time 🎊 . Maybe it would be a good idea to add an option to enable the timeout feature. 

I could look into it if you want and make PR :)
